#!/usr/bin/env perl

use 5.036;
use strict;
use warnings;
use utf8;

use English;
use Music::Harmonica::TabsCreator 'sheet_to_tab', 'get_tuning';

our $VERSION = '0.01';

BEGIN {
  my $has_locale = eval { require Encode::Locale; Encode::Locale->import(); 1 };
  if (-t STDIN && $has_locale) {
    binmode STDIN, ':encoding(console_in)';  # console_in is set by the Encode::Locale module.
  } else {
    binmode STDIN, ':encoding(UTF-8)';
  }
  if (-t STDOUT && $has_locale) {
    binmode STDOUT, ':encoding(console_out)';  # console_out is set by the Encode::Locale module.
  } else {
    binmode STDOUT, ':encoding(UTF-8)';
  }
  if (-t STDERR && $has_locale) {
    binmode STDERR, ':encoding(console_out)';  # console_out is set by the Encode::Locale module.
  } else {
    binmode STDOUT, ':encoding(UTF-8)';
  }
}

my $sheet;
{
  local $INPUT_RECORD_SEPARATOR = undef;
  $sheet = <>;
}

use Data::Dumper;
my %tabs = sheet_to_tab($sheet);

if (!%tabs) {
  say 'No tabs found';
  exit 0;
}

for my $type (sort keys %tabs) {
  my %details = get_tuning($type);
  printf "For %s %s harmonicas:\n", join(' ', @{$details{tags}}), $details{name};
  for my $key (sort keys %{$tabs{$type}}) {
    say "  in the key of ${key}:";
    for my $tab (@{$tabs{$type}{$key}}) {
      say '    '.join(' ', @{$tab});
    }
  }
}

__END__
