#!/usr/bin/env perl

use 5.036;
use strict;
use warnings;
use utf8;

use English;
use Music::Harmonica::TabsCreator 'sheet_to_tab_rendered';

our $VERSION = '0.01';

BEGIN {
  my $has_locale = eval { require Encode::Locale; Encode::Locale->import(); 1 };
  if (-t STDIN && $has_locale) {
    binmode STDIN, ':encoding(console_in)';  # console_in is set by the Encode::Locale module.
  } else {
    binmode STDIN, ':encoding(UTF-8)';
  }
  if (-t STDOUT && $has_locale) {
    binmode STDOUT, ':encoding(console_out)';  # console_out is set by the Encode::Locale module.
  } else {
    binmode STDOUT, ':encoding(UTF-8)';
  }
  if (-t STDERR && $has_locale) {
    binmode STDERR, ':encoding(console_out)';  # console_out is set by the Encode::Locale module.
  } else {
    binmode STDOUT, ':encoding(UTF-8)';
  }
}

my $sheet;
{
  local $INPUT_RECORD_SEPARATOR = undef;
  $sheet = <>;
}

say sheet_to_tab_rendered($sheet);

exit 0;

__END__
